# Generated by Django 4.0.4 on 2022-04-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='osrs_id',
        ),
    ]
