# Generated by Django 4.0.4 on 2022-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_item_id_item_osrs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='abc', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='osrs_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
