# Generated by Django 4.0.4 on 2022-04-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processitem_delete_processitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='app.itemgroup'),
        ),
    ]
